name: Auto Update

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
    - name: Commit and push if changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update: $(date)" && git push) 
